-- SUPERSEDED BY 20260322000000_fix_test_users_and_seed_metro.sql
--
-- This migration originally seeded "day 30" demo data (jobs, invoices,
-- routines, notifications, ops exceptions, provider applications, customer
-- credits) keyed off `d2000000-*` UUIDs and a hardcoded `v_property_id =
-- 'edfedf3d-251d-4de7-89a8-1ce5f439e12e'` that did not exist in
-- `public.properties` at the time this migration ran. On Supabase Preview
-- branches (which bootstrap fresh in strict timestamp order), the very first
-- `INSERT INTO jobs (..., property_id = v_property_id, ...)` fails with
-- `jobs_property_id_fkey` (SQLSTATE 23503) and blocks every PR's CI.
--
-- The later migration `20260322000000_fix_test_users_and_seed_metro.sql`
-- explicitly DELETEs every `d2000000-*` row this file would have created
-- (see that migration around lines 97–108), then replaces the demo data
-- with the richer Austin metro seed. Nothing downstream depends on the
-- rows this migration originally produced, so emptying it is safe.
--
-- Production impact: zero. This migration is already present in
-- `schema_migrations` on production, so its new empty content will never
-- re-run; `schema_migrations` tracks filename, not content hash.
--
-- Preview impact: the FK failure is gone. Mar 22's seed-metro migration
-- now seeds everything correctly on a fresh branch bootstrap.
--
-- Same pattern as commit `c3ba864` (PR #5), which emptied
-- `20260223032019` / `20260223034117` for the same class of reason.
