-- ============================================================
-- [2026-04-22] This migration was emptied out to unblock Supabase
-- preview-branch bootstrapping.
--
-- The original content was a demo-seed that INSERTed into
-- provider_coverage / subscriptions / jobs / service_day_assignments /
-- market_zone_category_state / growth_surface_config, all referencing
-- zone_id b1000000-0000-0000-0000-000000000001 and a set of auth user,
-- property, plan, and entitlement-version UUIDs that were not yet
-- created in the migration chain at this timestamp. Fresh preview
-- branches (which apply migrations top-to-bottom from empty state)
-- therefore failed with FK violations.
--
-- `20260322000000_fix_test_users_and_seed_metro.sql` ("fix_test_users")
-- is the comprehensive re-seed that supersedes this file — it creates
-- the auth users, zones, plans, entitlement versions, properties, AND
-- re-seeds every row this migration was trying to create, with
-- ON CONFLICT DO NOTHING, in correctly ordered FK-respecting sequence.
--
-- Production already has this migration tracked as applied in
-- schema_migrations, so emptying the file is a no-op on production.
-- Preview branches bootstrap from scratch and will run this as a
-- no-op, then pick up the authoritative seed from 20260322000000.
-- ============================================================

-- (intentionally empty; see header)
