-- ============================================================
-- [2026-04-22] This migration was emptied out to unblock Supabase
-- preview-branch bootstrapping.
--
-- The original content INSERTed a second test property, an offered
-- service_day_assignment with TTL, three service_day_offers, and
-- three share_cards — all referencing zone_id b1000000-... and an
-- auth user UUID that were not yet created in the migration chain
-- at this timestamp. Fresh preview branches failed with FK violations.
--
-- The content has been relocated verbatim to
-- `20260322000100_seed_gap_fix_secondary_property_and_share_cards.sql`,
-- which runs after `20260322000000_fix_test_users_and_seed_metro.sql`
-- creates the required auth user, zone, property parent, and jobs.
--
-- Production already has this migration tracked as applied in
-- schema_migrations, so emptying the file is a no-op on production.
-- The new post-Mar-22 migration also uses ON CONFLICT DO NOTHING, so
-- when production applies it for the first time it's idempotent
-- against any existing rows.
-- ============================================================

-- (intentionally empty; see header)
